# A sample Gemfile
source "https://rubygems.org"

gem 'aws-sdk'
gem 'deep_merge'
gem 'pg'
gem 'rubyzip'
gem 'pdfkit'
gem 'rmagick'
gem 'parallel'
gem 'logglier'
gem 'multi_json'
gem 'pry'
gem 'pry-remote'
